package com.founder.web.webservice.utils;

import java.util.HashMap;
import java.util.Map;

public class DictConstants4TabNameByMsgId {

	public static final Map<String, String> CONSTANTS_4TableName_MAP = new HashMap<String, String>();

	static {
		init();
	}

	private static void init() {
		CONSTANTS_4TableName_MAP.put("BS901", "IAM_ACCOUNT_INFO");
		// 组织信息时，涉及多张表，故暂无具体表对应。
		/*
		 * CONSTANTS_4TableName_MAP.put("BS902","3");
		 * CONSTANTS_4TableName_MAP.put("BS903","4");
		 * CONSTANTS_4TableName_MAP.put("BS904","5");
		 * CONSTANTS_4TableName_MAP.put("BS905","6");
		 * CONSTANTS_4TableName_MAP.put("BS906","7");
		 * CONSTANTS_4TableName_MAP.put("BS907","8");
		 * CONSTANTS_4TableName_MAP.put("BS908","9");
		 * CONSTANTS_4TableName_MAP.put("BS909","10");
		 * CONSTANTS_4TableName_MAP.put("MS001","11");
		 */
		CONSTANTS_4TableName_MAP.put("MS002", "DICT_ICD");
		CONSTANTS_4TableName_MAP.put("MS003", "DICT_ICD_EMR");
		CONSTANTS_4TableName_MAP.put("MS004", "DICT_OPERATION_OPERATE");
		CONSTANTS_4TableName_MAP.put("MS005", "DICT_SEX");
		CONSTANTS_4TableName_MAP.put("MS006", "DICT_NATION");
		CONSTANTS_4TableName_MAP.put("MS007", "DICT_OCCUPATION");
		CONSTANTS_4TableName_MAP.put("MS008", "DICT_MARRY");
		CONSTANTS_4TableName_MAP.put("MS009", "DICT_CULTURE_LEVEL");
		CONSTANTS_4TableName_MAP.put("MS010", "DICT_COUNTRY_NAME");
		CONSTANTS_4TableName_MAP.put("MS011", "DICT_DISTRICT");
		CONSTANTS_4TableName_MAP.put("MS012", "DICT_PATIENT_TYPE");
		CONSTANTS_4TableName_MAP.put("MS013", "DICT_ABO_BLOOD_TYPE");
		CONSTANTS_4TableName_MAP.put("MS014", "DICT_CERTIFICATES_TYPE");
		CONSTANTS_4TableName_MAP.put("MS015", "DICT_OPERATION_INCISION");
		CONSTANTS_4TableName_MAP.put("MS016", "DICT_DISEASE_DIAGNOSIS");
		CONSTANTS_4TableName_MAP.put("MS017", "DICT_ADMINISTRATION_ROUTE");
		CONSTANTS_4TableName_MAP.put("MS018", "DICT_PAY");
		CONSTANTS_4TableName_MAP.put("MS019", "DICT_MEDICINE_DOSAGE");
		CONSTANTS_4TableName_MAP.put("MS020", "DICT_SPECIMEN_TYPE");
		CONSTANTS_4TableName_MAP.put("MS021", "DICT_OUTPATIENT_COST");
		CONSTANTS_4TableName_MAP.put("MS022", "DICT_HOSPITAL_COST");
		CONSTANTS_4TableName_MAP.put("MS023", "DICT_TRANSFUSION_BLOOD");
		CONSTANTS_4TableName_MAP.put("MS024", "DICT_PERSON");
		CONSTANTS_4TableName_MAP.put("MS025", "DICT_DEPARTMENT");
		CONSTANTS_4TableName_MAP.put("MS026", "DICT_INPATIENT_AREA");
		CONSTANTS_4TableName_MAP.put("MS027", "DICT_MEDICINE_TYPE");
		CONSTANTS_4TableName_MAP.put("MS028", "DICT_DRUGS");
		CONSTANTS_4TableName_MAP.put("MS029", "DICT_EMPLOYMENTSTATUS");
		CONSTANTS_4TableName_MAP.put("MS030", "DICT_EMPLOYEETYPE");
		CONSTANTS_4TableName_MAP.put("MS031", "DICT_CHARGE_ITEM");
		CONSTANTS_4TableName_MAP.put("MS032", "DICT_RESPONCE_TYPE");
		CONSTANTS_4TableName_MAP.put("MS033", "DICT_INSPECTION_ITEM");
		CONSTANTS_4TableName_MAP.put("MS034", "DICT_INSPECTION_TYPE");
		CONSTANTS_4TableName_MAP.put("MS035", "DICT_CLINIC_DIAGNOSIS");
		CONSTANTS_4TableName_MAP.put("MS036", "DICT_ORDER_ITEM");
		CONSTANTS_4TableName_MAP.put("MS037", "DICT_CHARGE_TYPE");
		CONSTANTS_4TableName_MAP.put("MS038", "DICT_HIGH_PRICE");// 高值耗材字典
		CONSTANTS_4TableName_MAP.put("MS039", "DICT_CHECK_ITEM");
		CONSTANTS_4TableName_MAP.put("MS040", "DICT_CHECK_ITEM_GROUP");
		CONSTANTS_4TableName_MAP.put("MS041", "DICT_PATIENT_DOMAIN");
		CONSTANTS_4TableName_MAP.put("MS042", "DICT_LOW_PRICE"); // 低值耗材字典
		CONSTANTS_4TableName_MAP.put("MS043", "DICT_CHARGE_TEAM");
		CONSTANTS_4TableName_MAP.put("MS044", "DICT_HOLIDAY");
		CONSTANTS_4TableName_MAP.put("MS045", "DICT_PRESCRIPTION");
		CONSTANTS_4TableName_MAP.put("MS047", "DICT_OPERATE_AUTH");
		CONSTANTS_4TableName_MAP.put("MS048", "DICT_PERSON_TITLE_RELATION");
		CONSTANTS_4TableName_MAP.put("MS049", "DICT_PACING_MEASUREMENT");
		CONSTANTS_4TableName_MAP.put("MS050", "DICT_PHARMACEUTICAL_FACTORY");
		CONSTANTS_4TableName_MAP.put("MS051", "DICT_BLOOD_REQUIREMENT");
		CONSTANTS_4TableName_MAP.put("MS052", "DICT_MEDICAL_STORAGEROOM");
		CONSTANTS_4TableName_MAP.put("MS053", "DICT_MEDICAL_NAME");
		CONSTANTS_4TableName_MAP.put("MS054", "DICT_MEDICAL_WHOLESALER");
		CONSTANTS_4TableName_MAP.put("MS057", "DICT_DRUG_MARK");
		CONSTANTS_4TableName_MAP.put("MS058", "DICT_MEDICINE_CATEGORY");
		CONSTANTS_4TableName_MAP.put("MS059", "DICT_FREQUENCY");
		CONSTANTS_4TableName_MAP.put("MS060", "DICT_CHECK_TYPE");
		CONSTANTS_4TableName_MAP.put("MS061", "DICT_BLOOD_URGENT");
		CONSTANTS_4TableName_MAP.put("MS062", "DICT_FINANCIAL_DEPARTMENT");
		CONSTANTS_4TableName_MAP.put("MS063", "DICT_APPLY_INSPECTION");
		CONSTANTS_4TableName_MAP.put("MS064", "DICT_INSPECTION_SUB_ITEM");
		CONSTANTS_4TableName_MAP.put("MS067", "DICT_TITLE");
		CONSTANTS_4TableName_MAP.put("MS068", "DICT_RH_BLOOD_TYPE");
		CONSTANTS_4TableName_MAP.put("MS069", "DICT_PATIENT_RELATION");
		CONSTANTS_4TableName_MAP.put("MS070", "DICT_BLOOD_TRANSFUSION");
		CONSTANTS_4TableName_MAP.put("MS071", "DICT_CHECK_POSITION");
		CONSTANTS_4TableName_MAP.put("MS072", "DICT_ORDER_TYPE");
		CONSTANTS_4TableName_MAP.put("MS073", "DICT_ORDER_EXEC_STATE");
		CONSTANTS_4TableName_MAP.put("MS074", "DICT_CLINIC_STATE");
		CONSTANTS_4TableName_MAP.put("MS075", "DICT_PHYSICAL_EXAM");
		CONSTANTS_4TableName_MAP.put("MS076", "DICT_BOOLEAN");
		CONSTANTS_4TableName_MAP.put("MS077", "DICT_COST_STATE");
		CONSTANTS_4TableName_MAP.put("MS078", "DICT_BILL_TYPE");
		CONSTANTS_4TableName_MAP.put("MS066", "DICT_CUT_HEAL"); // 手术切口字典表
		CONSTANTS_4TableName_MAP.put("MS065", "DICT_CUT_TYPE"); // 手术愈合等级字典表
		CONSTANTS_4TableName_MAP.put("MS046", "DICT_DISPATCH_CD"); // 消息分类字典表
		CONSTANTS_4TableName_MAP.put("MS080", "DICT_LIS_ITEM_MAPPING"); // 医嘱与LIS检验项目关系字典
		CONSTANTS_4TableName_MAP.put("MS081", "DICT_CONTAINER_MAPPING"); // LIS检验项目与容器关系字典
		CONSTANTS_4TableName_MAP.put("MS082", "DICT_CONTAINER_INFO"); // 容器字典
	}
}
